# Assignment 1 – Classification Dataset Analysis

Name: Amrita Kumari  
File Name: AmritaKumari.ipynb  

Dataset Name: Customer Churn Dataset  

Dataset Link (kaggle Direct Link):
Customer Churn Dataset https://share.google/gQAtn2WcTbixWJCiu

In [25]:
# select a real-world classification dataset (e.g.,spam detection,loan approval,diseas prediction,customer churn).
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report, precision_score, recall_score, f1_score

In [5]:
data = pd.read_csv(r"C:\Users\kumar\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\B83401E200B1E553821E362ED92FB50873A9C424\transfers\2026-08\loanapproval.csv")
data.head()

,applicant_id,age,gender,marital_status,annual_income,loan_amount,credit_score,num_dependents,existing_loans_count,employment_status,loan_approved
0,1,59,Male,Divorced,100073,7169,793,1,1,Unemployed,1
1,2,49,Male,Married,112197,23556,789,0,2,Employed,1
2,3,35,Male,Divorced,84429,27052,372,1,4,Unemployed,0
3,4,63,Female,Single,124195,11313,808,3,4,Self-employed,1
4,5,28,Female,Married,81627,13315,689,0,1,Unemployed,1

In [30]:
data.shape

(1000, 13)

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 13 columns):
 #   Column                           Non-Null Count  Dtype
---  ------                           --------------  -----
 0   applicant_id                     1000 non-null   int64
 1   age                              1000 non-null   int64
 2   annual_income                    1000 non-null   int64
 3   loan_amount                      1000 non-null   int64
 4   credit_score                     1000 non-null   int64
 5   num_dependents                   1000 non-null   int64
 6   existing_loans_count             1000 non-null   int64
 7   loan_approved                    1000 non-null   int64
 8   gender_Male                      1000 non-null   bool
 9   marital_status_Married           1000 non-null   bool
 10  marital_status_Single            1000 non-null   bool
 11  employment_status_Self-employed  1000 non-null   bool
 12  employment_status_Unemployed     1000 non-null   bool
dtypes: bool(5), int64(8)
memory usage: 67.5 KB

In [34]:
data.isnull().sum()

applicant_id                       0
age                                0
annual_income                      0
loan_amount                        0
credit_score                       0
num_dependents                     0
existing_loans_count               0
loan_approved                      0
gender_Male                        0
marital_status_Married             0
marital_status_Single              0
employment_status_Self-employed    0
employment_status_Unemployed       0
dtype: int64

In [35]:

# Fill numerical columns
data.fillna(data.mean(numeric_only=True), inplace=True)

# Fill categorical columns
for col in data.select_dtypes(include='object').columns:
    data[col] = data[col].fillna(data[col].mode()[0])

data.isnull().sum()

applicant_id                       0
age                                0
annual_income                      0
loan_amount                        0
credit_score                       0
num_dependents                     0
existing_loans_count               0
loan_approved                      0
gender_Male                        0
marital_status_Married             0
marital_status_Single              0
employment_status_Self-employed    0
employment_status_Unemployed       0
dtype: int64

In [40]:
"Loan_Status"

'Loan_Status'

In [45]:
print(data.columns)

Index(['applicant_id', 'age', 'annual_income', 'loan_amount', 'credit_score',
       'num_dependents', 'existing_loans_count', 'loan_approved',
       'gender_Male', 'marital_status_Married', 'marital_status_Single',
       'employment_status_Self-employed', 'employment_status_Unemployed'],
      dtype='object')

In [36]:
#using label encoding
data = pd.get_dummies(data, drop_first=True)
data.head()

,applicant_id,age,annual_income,loan_amount,credit_score,num_dependents,existing_loans_count,loan_approved,gender_Male,marital_status_Married,marital_status_Single,employment_status_Self-employed,employment_status_Unemployed
0,1,59,100073,7169,793,1,1,1,True,False,False,False,True
1,2,49,112197,23556,789,0,2,1,True,True,False,False,False
2,3,35,84429,27052,372,1,4,0,True,False,False,False,True
3,4,63,124195,11313,808,3,4,1,False,False,True,True,False
4,5,28,81627,13315,689,0,1,1,False,True,False,False,True

In [21]:
data = pd.get_dummies(data, drop_first=True)
data.head()

,applicant_id,age,annual_income,loan_amount,credit_score,num_dependents,existing_loans_count,loan_approved,gender_Male,marital_status_Married,marital_status_Single,employment_status_Self-employed,employment_status_Unemployed
0,1,59,100073,7169,793,1,1,1,True,False,False,False,True
1,2,49,112197,23556,789,0,2,1,True,True,False,False,False
2,3,35,84429,27052,372,1,4,0,True,False,False,False,True
3,4,63,124195,11313,808,3,4,1,False,False,True,True,False
4,5,28,81627,13315,689,0,1,1,False,True,False,False,True

In [48]:
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

NameError: name 'X_train' is not defined

In [14]:
#Normalize/Standardize
scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

print(X_train.shape)
print(X_test.shape)
print(X_train[:5])

In [1]:
# Perform data preprocessing:handle missing values,encode categorical variables,and normalize/standardize feature.
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [3]:
data = pd.read_csv(r"C:\Users\kumar\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\B83401E200B1E553821E362ED92FB50873A9C424\transfers\2026-06\customer_churn_dataset-testing-master.csv")
data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [4]:
data.isnull().sum()
# For numerical columns
data.fillna(data.mean(numeric_only=True), inplace=True)

# For categorical columns
data.fillna(data.mode().iloc[0], inplace=True)

In [6]:
import pandas as pd

In [7]:
data = pd.read_csv(r"C:\Users\kumar\AppData\Local\Packages\5319275A.WhatsAppDesktop_cv1g1gvanyjgm\LocalState\sessions\B83401E200B1E553821E362ED92FB50873A9C424\transfers\2026-06\customer_churn_dataset-testing-master.csv")
data.head()

,CustomerID,Age,Gender,Tenure,Usage Frequency,Support Calls,Payment Delay,Subscription Type,Contract Length,Total Spend,Last Interaction,Churn
0,1,22,Female,25,14,4,27,Basic,Monthly,598,9,1
1,2,41,Female,28,28,7,13,Standard,Monthly,584,20,0
2,3,47,Male,27,10,2,29,Premium,Annual,757,21,0
3,4,35,Male,9,12,5,17,Premium,Quarterly,232,18,0
4,5,53,Female,58,24,9,2,Standard,Annual,533,18,0

In [10]:
data = pd.get_dummies(data, drop_first=True)
print(data.head())

   CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0           1   22      25               14              4             27
1           2   41      28               28              7             13
2           3   47      27               10              2             29
3           4   35       9               12              5             17
4           5   53      58               24              9              2

   Total Spend  Last Interaction  Churn  Gender_Male  \
0          598                 9      1        False
1          584                20      0        False
2          757                21      0         True
3          232                18      0         True
4          533                18      0        False

   Subscription Type_Premium  Subscription Type_Standard  \
0                      False                       False
1                      False                        True
2                       True                       False
3                       True                       False
4                      False                        True

   Contract Length_Monthly  Contract Length_Quarterly
0                     True                      False
1                     True                      False
2                    False                      False
3                    False                       True
4                    False                      False

In [8]:
# For numerical columns
data.fillna(data.mean(numeric_only=True), inplace=True)
# For categorical columns
data.fillna(data.mode().iloc[0], inplace=True)
data.isnull().sum()

CustomerID           0
Age                  0
Gender               0
Tenure               0
Usage Frequency      0
Support Calls        0
Payment Delay        0
Subscription Type    0
Contract Length      0
Total Spend          0
Last Interaction     0
Churn                0
dtype: int64

In [11]:
X = data.drop("Churn", axis=1)   # Target column name
y = data["Churn"]
print(X.head())
print(y.head())

   CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0           1   22      25               14              4             27
1           2   41      28               28              7             13
2           3   47      27               10              2             29
3           4   35       9               12              5             17
4           5   53      58               24              9              2

   Total Spend  Last Interaction  Gender_Male  Subscription Type_Premium  \
0          598                 9        False                      False
1          584                20        False                      False
2          757                21         True                       True
3          232                18         True                       True
4          533                18        False                      False

   Subscription Type_Standard  Contract Length_Monthly  \
0                       False                     True
1                        True                     True
2                       False                    False
3                       False                    False
4                        True                    False

   Contract Length_Quarterly
0                      False
1                      False
2                      False
3                       True
4                      False
0    1
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64

In [7]:
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)

(51499, 13)
(12875, 13)

In [29]:
X = data.drop("Churn", axis=1)
y = data["Churn"]
print(X.head())
print(y.head())
print(X.shape)
print(y.shape)
print(X)
print(y)

   CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0           1   22      25               14              4             27
1           2   41      28               28              7             13
2           3   47      27               10              2             29
3           4   35       9               12              5             17
4           5   53      58               24              9              2

   Total Spend  Last Interaction  Gender_Male  Subscription Type_Premium  \
0          598                 9        False                      False
1          584                20        False                      False
2          757                21         True                       True
3          232                18         True                       True
4          533                18        False                      False

   Subscription Type_Standard  Contract Length_Monthly  \
0                       False                     True
1                        True                     True
2                       False                    False
3                       False                    False
4                        True                    False

   Contract Length_Quarterly
0                      False
1                      False
2                      False
3                       True
4                      False
0    1
1    0
2    0
3    0
4    0
Name: Churn, dtype: int64
(64374, 13)
(64374,)
       CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
0               1   22      25               14              4             27
1               2   41      28               28              7             13
2               3   47      27               10              2             29
3               4   35       9               12              5             17
4               5   53      58               24              9              2
...           ...  ...     ...              ...            ...            ...
64369       64370   45      33               12              6             21
64370       64371   37       6                1              5             22
64371       64372   25      39               14              8             30
64372       64373   50      18               19              7             22
64373       64374   52      45               15              9             25

       Total Spend  Last Interaction  Gender_Male  Subscription Type_Premium  \
0              598                 9        False                      False
1              584                20        False                      False
2              757                21         True                       True
3              232                18         True                       True
4              533                18        False                      False
...            ...               ...          ...                        ...
64369          947                14        False                      False
64370          923                 9         True                      False
64371          327                20         True                       True
64372          540                13        False                      False
64373          696                22        False                      False

       Subscription Type_Standard  Contract Length_Monthly  \
0                           False                     True
1                            True                     True
2                           False                    False
3                           False                    False
4                            True                    False
...                           ...                      ...
64369                       False                    False
64370                        True                    False
64371                       False                     True
64372                        True                     True
64373                        True                     True

       Contract Length_Quarterly
0                          False
1                          False
2                          False
3                           True
4                          False
...                          ...
64369                       True
64370                      False
64371                      False
64372                      False
64373                      False

[64374 rows x 13 columns]
0        1
1        0
2        0
3        0
4        0
        ..
64369    1
64370    1
64371    1
64372    1
64373    1
Name: Churn, Length: 64374, dtype: int64

In [30]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)
print("X_train:")
print(X_train.head())

print("\nX_test:")
print(X_test.head())

print("\ny_train:")
print(y_train.head())

print("\ny_test:")
print(y_test.head())

X_train:
       CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
13468       13469   56      42               11              0             10
20118       20119   54      60                5              3              9
48411       48412   31      12                2              9              7
42125       42126   33      22               17              5             25
55119       55120   39      28               30              2             25

       Total Spend  Last Interaction  Gender_Male  Subscription Type_Premium  \
13468          793                15        False                       True
20118          610                24         True                      False
48411          222                30         True                      False
42125          648                20        False                       True
55119          983                22        False                       True

       Subscription Type_Standard  Contract Length_Monthly  \
13468                       False                    False
20118                        True                    False
48411                       False                    False
42125                       False                     True
55119                       False                     True

       Contract Length_Quarterly
13468                       True
20118                       True
48411                      False
42125                      False
55119                      False

X_test:
       CustomerID  Age  Tenure  Usage Frequency  Support Calls  Payment Delay  \
15476       15477   55      20               24              4              6
34666       34667   28      27               30              4              5
50474       50475   65      60               17              7             16
7984         7985   53      47               16              8              7
20227       20228   32      56                5              7             15

       Total Spend  Last Interaction  Gender_Male  Subscription Type_Premium  \
15476          635                25         True                      False
34666          631                10         True                       True
50474          314                 1        False                       True
7984           527                13         True                       True
20227          236                25         True                       True

       Subscription Type_Standard  Contract Length_Monthly  \
15476                        True                     True
34666                       False                    False
50474                       False                    False
7984                        False                    False
20227                       False                    False

       Contract Length_Quarterly
15476                      False
34666                       True
50474                       True
7984                       False
20227                      False

y_train:
13468    0
20118    0
48411    1
42125    1
55119    1
Name: Churn, dtype: int64

y_test:
15476    0
34666    0
50474    1
7984     0
20227    0
Name: Churn, dtype: int64

In [23]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

In [31]:
print("X_train shape:", X_train.shape)
print("X_test shape:", X_test.shape)
print("y_train shape:", y_train.shape)
print("y_test shape:", y_test.shape)

X_train shape: (51499, 13)
X_test shape: (12875, 13)
y_train shape: (51499,)
y_test shape: (12875,)

In [39]:
# Implement at least two classification algorithm (eg.,Logistic Regression,Decision Tree,K-Nearest Neighbours,Naive bayes,Support vector machine).
from sklearn.linear_model import LogisticRegression

lr = LogisticRegression()
lr.fit(X_train, y_train)

y_pred_lr = lr.predict(X_test)
print(y_pred_lr)
print(y_pred_lr[:10])   # First 10 predictions
print("Actual:", y_test.values[:10])
print("Predicted:", y_pred_lr[:10])
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_lr))
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_lr))
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_lr))

[0 0 1 ... 1 0 0]
[0 0 1 0 1 0 0 0 0 0]
Actual: [0 0 1 0 0 0 0 0 1 0]
Predicted: [0 0 1 0 1 0 0 0 0 0]
Accuracy: 0.7947184466019418
[[5270 1523]
 [1120 4962]]
              precision    recall  f1-score   support

           0       0.82      0.78      0.80      6793
           1       0.77      0.82      0.79      6082

    accuracy                           0.79     12875
   macro avg       0.79      0.80      0.79     12875
weighted avg       0.80      0.79      0.79     12875

C:\Users\kumar\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\linear_model\_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [47]:
# Decision Tree
from sklearn.tree import DecisionTreeClassifier

dt = DecisionTreeClassifier()
dt.fit(X_train, y_train)

y_pred_dt = dt.predict(X_test)
print(y_pred_dt)
print(y_pred_dt[:10])   # First 10 predictions
print("Actual:", y_test.values[:10])
print("Predicted:", y_pred_dt[:10])
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_dt))
from sklearn.metrics import confusion_matrix       # confusion Matrix

print(confusion_matrix(y_test, y_pred_dt))
from sklearn.metrics import classification_report  #classification Report

print(classification_report(y_test, y_pred_dt))

[0 0 1 ... 1 0 0]
[0 0 1 0 0 0 0 0 1 0]
Actual: [0 0 1 0 0 0 0 0 1 0]
Predicted: [0 0 1 0 0 0 0 0 1 0]
Accuracy: 0.9966601941747573
Accuracy: 0.9966601941747573
[[6771   22]
 [  21 6061]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      6793
           1       1.00      1.00      1.00      6082

    accuracy                           1.00     12875
   macro avg       1.00      1.00      1.00     12875
weighted avg       1.00      1.00      1.00     12875

In [51]:
# K-Nearest Neighbours
from sklearn.neighbors import KNeighborsClassifier

knn = KNeighborsClassifier(n_neighbors=5)
knn.fit(X_train, y_train)

y_pred_knn = knn.predict(X_test)
#Print Predicted Values
print(y_pred_knn)
print(y_pred_knn[:10])
#Compare Actual vs Predicted
print("Actual:", y_test.values[:10])
print("Predicted:", y_pred_knn[:10])
#Print Accuracy (Very Important)
from sklearn.metrics import accuracy_score

print("Accuracy:", accuracy_score(y_test, y_pred_knn))
#Confusion Matrix
from sklearn.metrics import confusion_matrix

print(confusion_matrix(y_test, y_pred_knn))
#Classification Report
from sklearn.metrics import classification_report

print(classification_report(y_test, y_pred_knn))
print("Logistic Regression Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Decision Tree Accuracy:", accuracy_score(y_test, y_pred_dt))
print("KNN Accuracy:", accuracy_score(y_test, y_pred_knn))

[0 0 1 ... 1 0 0]
[0 0 1 0 0 0 0 0 0 0]
Actual: [0 0 1 0 0 0 0 0 1 0]
Predicted: [0 0 1 0 0 0 0 0 0 0]
Accuracy: 0.7836893203883495
[[6005  788]
 [1997 4085]]
              precision    recall  f1-score   support

           0       0.75      0.88      0.81      6793
           1       0.84      0.67      0.75      6082

    accuracy                           0.78     12875
   macro avg       0.79      0.78      0.78     12875
weighted avg       0.79      0.78      0.78     12875

Logistic Regression Accuracy: 0.7947184466019418
Decision Tree Accuracy: 0.9966601941747573
KNN Accuracy: 0.7836893203883495

In [12]:
# 4 question Model Evaluation
from sklearn.metrics import accuracy_score, precision_score, recall_score, f1_score, confusion_matrix

In [13]:
# Evaluate each model using appropriate metrices such as accuracy,pricision,recall,F1,-score,and confusion matrix. 
print("Logistic Regression Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_lr))
print("Precision:", precision_score(y_test, y_pred_lr))
print("Recall:", recall_score(y_test, y_pred_lr))
print("F1 Score:", f1_score(y_test, y_pred_lr))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_lr))

Logistic Regression Results:
Accuracy: 0.8651650485436894
Precision: 0.8585808580858085
Recall: 0.8554751726405787
F1 Score: 0.8570252017789491
Confusion Matrix:
 [[5936  857]
 [ 879 5203]]

In [14]:
# Evaluate Decision Tree
print("Decision Tree Results:")
print("Accuracy:", accuracy_score(y_test, y_pred_dt))
print("Precision:", precision_score(y_test, y_pred_dt))
print("Recall:", recall_score(y_test, y_pred_dt))
print("F1 Score:", f1_score(y_test, y_pred_dt))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred_dt))

Decision Tree Results:
Accuracy: 0.996504854368932
Precision: 0.9962189709025152
Recall: 0.996382768826044
F1 Score: 0.9963008631319359
Confusion Matrix:
 [[6770   23]
 [  22 6060]]

In [15]:
new_prediction = lr.predict(X_test[:5])
print(new_prediction)

[0 0 1 0 0]

In [52]:
from sklearn.metrics import accuracy_score

acc_lr = accuracy_score(y_test, y_pred_lr)
acc_dt = accuracy_score(y_test, y_pred_dt)
acc_knn = accuracy_score(y_test, y_pred_knn)
print("Logistic Regression Accuracy:", acc_lr)
print("Decision Tree Accuracy:", acc_dt)
print("KNN Accuracy:", acc_knn)

Logistic Regression Accuracy: 0.7947184466019418
Decision Tree Accuracy: 0.9966601941747573
KNN Accuracy: 0.7836893203883495

In [18]:
# Best performing model
accuracies = {
    "Logistic Regression": acc_lr,
    "Decision Tree": acc_dt,
    "KNN": acc_knn
}

best_model = max(accuracies, key=accuracies.get)

print("Best Model:", best_model)
print("Highest Accuracy:", accuracies[best_model])

Best Model: Decision Tree
Highest Accuracy: 0.996504854368932